apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-build-service-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: build-service-availability
    interval: 1m
    rules:
    - alert: BuildServiceDown
      expr: |
        konflux_up{
          namespace="build-service",
          check="replicas-available",
          service="build-service"
        } != 1
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          build-service is down in cluster {{ $labels.source_cluster }}
        description: >
          The build-service pod has been down for 5min in cluster {{ $labels.source_cluster }}
        team: build
        alert_team_handle: <!subteam^S03DM1RL0TF>
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/build-service/build-service-availability.md
