apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: rhtap-image-controller-alerting
  labels:
    tenant: rhtap
spec:
  groups:
  - name: image-controller-availability
    interval: 1m
    rules:
    - alert: ImageControllerDown
      expr: |
        konflux_up{
          namespace="image-controller",
          check="replicas-available",
          service="image-controller"
        } != 1
      for: 5m
      labels:
        severity: critical
        slo: "true"
      annotations:
        summary: >-
          image-controller is down in cluster {{ $labels.source_cluster }}
        description: >
          The image-controller pod has been down for 5min in cluster {{ $labels.source_cluster }}
        team: build
        alert_team_handle: <!subteam^S03DM1RL0TF>
        runbook_url: https://gitlab.cee.redhat.com/konflux/docs/sop/-/blob/main/image-controller/image-controller-availability.md
